name: Setup Standard Workflow
description: Setups the repo for CI
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"
    - name: Print versions
      shell: bash
      run: node --version && pnpm --version
    - name: Install project dependencies
      shell: bash
      run: pnpm install
